### ISSUE TITLE
How to auto-manage inter-crate dependency versions?

### ISSUE THREAD

**Issue by chrisjsewell** [chrisjsewell/markdown-it-plugins.rs#14]
If you have e.g.

```toml
[dependencies]
gfm-autolinks = { path = "../gfm-autolinks" }
```

then this cannot be published, because `path` is stripped from crate.io uploads

but then how to ensure that the version is always the latest AND ensure that unreleased changes to the dependency are released, before the version is updated and the package released.

```toml
[dependencies]
gfm-autolinks = { path = "../gfm-autolinks", version = "0.1" }
```
